
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seeley-c
 */
public class pokeGUI extends javax.swing.JFrame {

    /**
     * Creates new form pokeGUI
     */
    public pokeGUI() {
        initComponents();
    }
    
    
    protected Controller c;			// controller object
    protected DefaultListModel pokeListModel = new DefaultListModel();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CatchNewPoke = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newPokeInfo = new javax.swing.JTextArea();
        KeepButton = new javax.swing.JButton();
        DiscardButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PokeList = new javax.swing.JScrollPane();
        pokeList = new javax.swing.JList<>();
        PokeInfo = new javax.swing.JPanel();
        TrainButton = new javax.swing.JButton();
        RenameButton = new javax.swing.JButton();
        ReleaseButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pokeDetailTxt = new javax.swing.JTextArea();
        enterName = new javax.swing.JTextField();
        SubmitNameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PokeInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        CatchNewPoke.setText("Catch New Pokemon");
        CatchNewPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatchNewPokeActionPerformed(evt);
            }
        });

        newPokeInfo.setColumns(20);
        newPokeInfo.setRows(5);
        jScrollPane2.setViewportView(newPokeInfo);

        KeepButton.setText("Keep");
        KeepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeepButtonActionPerformed(evt);
            }
        });

        DiscardButton.setText("Discard");
        DiscardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CatchNewPoke, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiscardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CatchNewPoke, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KeepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(DiscardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        pokeList.setModel(pokeListModel);
        pokeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                pokeListValueChanged(evt);
            }
        });
        PokeList.setViewportView(pokeList);

        PokeInfo.setBackground(new java.awt.Color(0, 153, 255));

        TrainButton.setText("Train");
        TrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainButtonActionPerformed(evt);
            }
        });

        RenameButton.setText("Change Name");
        RenameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenameButtonActionPerformed(evt);
            }
        });

        ReleaseButton.setBackground(new java.awt.Color(204, 0, 0));
        ReleaseButton.setForeground(new java.awt.Color(255, 255, 255));
        ReleaseButton.setText("Release");
        ReleaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReleaseButtonActionPerformed(evt);
            }
        });

        pokeDetailTxt.setColumns(20);
        pokeDetailTxt.setRows(5);
        jScrollPane3.setViewportView(pokeDetailTxt);

        enterName.setText("Enter Name");

        SubmitNameButton.setText("Submit");
        SubmitNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PokeInfoLayout = new javax.swing.GroupLayout(PokeInfo);
        PokeInfo.setLayout(PokeInfoLayout);
        PokeInfoLayout.setHorizontalGroup(
            PokeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PokeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PokeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PokeInfoLayout.createSequentialGroup()
                        .addComponent(TrainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReleaseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RenameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterName, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitNameButton))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        PokeInfoLayout.setVerticalGroup(
            PokeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PokeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PokeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrainButton)
                    .addComponent(RenameButton)
                    .addComponent(enterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReleaseButton)
                    .addComponent(SubmitNameButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Captured Pokemon:");

        PokeInfoLabel.setText("Your Pokemon Info:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PokeList, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PokeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PokeInfoLabel)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PokeInfoLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PokeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PokeList)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void KeepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeepButtonActionPerformed
        c.keepGenPoke();
        this.clearText();//clear text field
        
        
        KeepButton.setEnabled(false);
        DiscardButton.setEnabled(false);
    }//GEN-LAST:event_KeepButtonActionPerformed

    private void DiscardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardButtonActionPerformed
        this.clearText();//clear text field
        KeepButton.setEnabled(false);
        DiscardButton.setEnabled(false);
    }//GEN-LAST:event_DiscardButtonActionPerformed

    private void CatchNewPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatchNewPokeActionPerformed
        c.createPoke();
        newPokeInfo.setText(c.toStringPoke());
        KeepButton.setEnabled(true);
        DiscardButton.setEnabled(true);
    }//GEN-LAST:event_CatchNewPokeActionPerformed

    private void TrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainButtonActionPerformed

        pokeDetailTxt.setText(c.trainPoke());
    }//GEN-LAST:event_TrainButtonActionPerformed

    private void RenameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenameButtonActionPerformed
        enterName.setEnabled(true);
        SubmitNameButton.setEnabled(true);
    }//GEN-LAST:event_RenameButtonActionPerformed

    private void ReleaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReleaseButtonActionPerformed
        int n = pokeList.getSelectedIndex();
        
        if (n != -1) {
            //c.releasePoke(n);
            pokeListModel.remove(n);
        }
        
        pokeDetailTxt.setText("You just released the Pokemon");
    }//GEN-LAST:event_ReleaseButtonActionPerformed

    private void SubmitNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitNameButtonActionPerformed
        int n = pokeList.getSelectedIndex();
        String nm = enterName.getText();
        
        c.renamePoke(nm);
        
        enterName.setEnabled(false);
        SubmitNameButton.setEnabled(false);
        pokeDetailTxt.setText(c.getPoke(n));
    }//GEN-LAST:event_SubmitNameButtonActionPerformed

    private void pokeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_pokeListValueChanged
        int n = pokeList.getSelectedIndex();
        pokeDetailTxt.setText(c.getPoke(n));
        
        enterName.setEnabled(false);
        SubmitNameButton.setEnabled(false);
    }//GEN-LAST:event_pokeListValueChanged

    
    //*****************************************************
    // Purpose: add a contoller object to this ui
    // Interface: IN: Controller object c
    // Returns: none
    // ***************************************************** 
	 protected void addController(Controller c){
		 this.c = c;
	 } // end addUI	
         
         protected void clearText() {
             newPokeInfo.setText("");
         } //end clearText
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CatchNewPoke;
    private javax.swing.JButton DiscardButton;
    private javax.swing.JButton KeepButton;
    private javax.swing.JPanel PokeInfo;
    private javax.swing.JLabel PokeInfoLabel;
    private javax.swing.JScrollPane PokeList;
    private javax.swing.JButton ReleaseButton;
    private javax.swing.JButton RenameButton;
    private javax.swing.JButton SubmitNameButton;
    private javax.swing.JButton TrainButton;
    private javax.swing.JTextField enterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea newPokeInfo;
    private javax.swing.JTextArea pokeDetailTxt;
    private javax.swing.JList<String> pokeList;
    // End of variables declaration//GEN-END:variables
}
